apiVersion: v1
kind: Endpoints
metadata:
  name: mongo
subsets:
  - addresses:
      - ip: 10.30.7.30
    ports:
      - port: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
